name: my-wave-portal
run-name: ${{ github.actor }} is running Github Actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npx hardhat test